from django.contrib import admin
from .models import MTN,GLO,AIRTEL,DSTV,DSTV,GOTV,STARTIMES,ELECTRICITY,EXAM
# Register your models here.

admin.site.register(MTN)
admin.site.register(GLO)
admin.site.register(AIRTEL)
admin.site.register(DSTV)
admin.site.register(GOTV)
admin.site.register(STARTIMES)
admin.site.register(ELECTRICITY)
admin.site.register(EXAM)

from .models import Withdrawal, MTN_AIRTIME,GLO_AIRTIME,AIRTEL_AIRTIME,MTN_AWUF_AIRTIME,MTN_SHARE_AIRTIME,MTN_500MB_SME,MTN_2GB_SME,MTN_1GB_SME,MTN_3GB_SME,MTN_4GB_SME,MTN_5GB_SME,MTN_10GB_SME,MTN_1GB_WD,MTN_1P5GB_MD,MTN_2GB_MD,MTN_20GB_WD,GLO_50MB,GLO_150MB,GLO_350MB,GLO_2P9GB,GLO_4P1GB,GLO_5P8GB,GLO_7P7GB,GLO_13P75GB,GLO_18P25GB,AIRTEL_750MB,AIRTEL_1GB,AIRTEL_2GB,AIRTEL_3GB,AIRTEL_6GB,AIRTEL_10GB,AIRTEL_20GB,DSTV_PADI,DSTV_XTRAVIEW,DSTV_ASIAN_ADDON,DSTV_FRENCH_BOUGUET,DSTV_COMPACT_PLUS_F,DSTV_CONFAM,DSTV_YANGA, DSTV_PREMIUM,DSTV_COMPACT_PLUS,DSTV_COMPACT_PLUS_ASIAN_ADDON,GOTV_JOLLI,GOTV_SMALLIE,GOTV_LITE_QUART,GOTV_LITE_YEAR, GOTV_MAX,GOTV_JINJA,STARTIME_SMART_M,STARTIME_BASIC_M,STARTIME_CLASSIC_M,STARTIME_NOVA_M,STARTIME_SMART_W,STARTIME_BASIC_W,STARTIME_CLASSIC_W,STARTIME_NOVA_W,STARTIME_SMART_D,STARTIME_NOVA_D,STARTIME_BASIC_D,STARTIME_CLASSIC_D,ELECT_EKO_PRE,ELECT_IKEJA_PRE,ELECT_IBADAN_PRE,ELECT_ENUGU_PRE,ELECT_IKEJA_POST, ELECT_IBADAN_POST,ELECT_EKO_POST,ELECT_ENUGU_POST,WAEC,NECO
# Register your models here.


admin.site.register(MTN_AIRTIME )
admin.site.register(GLO_AIRTIME)
admin.site.register(AIRTEL_AIRTIME)
admin.site.register(MTN_AWUF_AIRTIME )
admin.site.register( MTN_SHARE_AIRTIME )
admin.site.register(MTN_500MB_SME  )
admin.site.register(  MTN_1GB_SME)
admin.site.register(  MTN_2GB_SME)
admin.site.register(  MTN_3GB_SME)
admin.site.register(  MTN_4GB_SME)
admin.site.register(  MTN_5GB_SME)
admin.site.register(  MTN_10GB_SME)
admin.site.register(  MTN_1GB_WD)
admin.site.register(  MTN_1P5GB_MD)
admin.site.register(  MTN_2GB_MD)
admin.site.register(  MTN_20GB_WD)
admin.site.register( GLO_150MB)
admin.site.register( GLO_350MB)
admin.site.register( GLO_2P9GB)
admin.site.register( GLO_4P1GB)
admin.site.register( GLO_5P8GB)
admin.site.register( GLO_7P7GB)
admin.site.register( GLO_13P75GB)
admin.site.register( GLO_18P25GB)
admin.site.register( AIRTEL_750MB)
admin.site.register(  AIRTEL_1GB)
admin.site.register( AIRTEL_2GB)
admin.site.register( AIRTEL_3GB)
admin.site.register( AIRTEL_6GB)
admin.site.register(  AIRTEL_10GB)
admin.site.register(  AIRTEL_20GB)
admin.site.register( DSTV_PADI)
admin.site.register( DSTV_XTRAVIEW)
admin.site.register( DSTV_ASIAN_ADDON)
admin.site.register( DSTV_FRENCH_BOUGUET)
admin.site.register(  DSTV_COMPACT_PLUS_F)
admin.site.register( DSTV_CONFAM)
admin.site.register( DSTV_YANGA)
admin.site.register(  DSTV_PREMIUM)
admin.site.register( DSTV_COMPACT_PLUS)
admin.site.register( DSTV_COMPACT_PLUS_ASIAN_ADDON)
admin.site.register( GOTV_JOLLI)
admin.site.register( GOTV_SMALLIE)
admin.site.register( GOTV_LITE_QUART)
admin.site.register( GOTV_LITE_YEAR)
admin.site.register(  GOTV_MAX)
admin.site.register( GOTV_JINJA)
admin.site.register( STARTIME_SMART_M)
admin.site.register( STARTIME_BASIC_M)
admin.site.register( STARTIME_CLASSIC_M)
admin.site.register( STARTIME_NOVA_M)
admin.site.register( STARTIME_SMART_W)
admin.site.register( STARTIME_BASIC_W)
admin.site.register( STARTIME_CLASSIC_W )
admin.site.register( STARTIME_NOVA_W)
admin.site.register( STARTIME_SMART_D)
admin.site.register( STARTIME_BASIC_D)
admin.site.register( STARTIME_CLASSIC_D)
admin.site.register(STARTIME_NOVA_D)
admin.site.register( ELECT_EKO_PRE)
admin.site.register( ELECT_IKEJA_PRE)
admin.site.register( ELECT_IBADAN_PRE)
admin.site.register( ELECT_ENUGU_PRE)
admin.site.register( ELECT_EKO_POST)
admin.site.register( ELECT_IKEJA_POST)
admin.site.register(  ELECT_IBADAN_POST)
admin.site.register( ELECT_ENUGU_POST)
admin.site.register(WAEC)
admin.site.register(NECO)
