from django.conf.urls import url
from django.urls import path
from . import views


from .views import withdrawal_view,airtime1_view,airtime2_view,airtime4_view,airtime5_view,airtime6_view,mtn1_view,mtn2_view,mtn3_view,mtn4_view,mtn5_view,mtn6_view,mtn7_view,mtn8_view,mtn9_view,mtn10_view,glo1_view,glo2_view,glo3_view,glo4_view,glo5_view,glo6_view,glo7_view,glo8_view,glo9_view,glo10_view,airtel1_view,airtel2_view,airtel3_view,airtel4_view,airtel5_view,airtel6_view,airtel7_view,airtel8_view,dstv1_view,dstv2_view,dstv3_view,dstv4_view,dstv5_view,dstv6_view,dstv7_view,dstv8_view,dstv9_view,dstv10_view,startime1_view,startime2_view,startime3_view,startime4_view,startime5_view,startime6_view,startime7_view,startime8_view,startime9_view,startime10_view,startime11_view,startime12_view,startime13_view,elect1_view,elect2_view,elect3_view,elect4_view,elect5_view,elect6_view,elect7_view,elect8_view,waec_view,neco_view,gotv1_view,gotv2_view,gotv3_view,gotv4_view,gotv5_view,gotv6_view,order1_view,order2_view,order4_view,order5_view,order6_view,order7_view,order8_view,order9_view,order3_view

app_name = 'transactions'

urlpatterns = [
    # url(r'^$', home_view, name='home'),
    url(r'^airtime1/$', airtime1_view, name='airtime1'),
    url(r'^airtime2/$', airtime2_view, name='airtime2'),
    url(r'^airtime4/$', airtime4_view, name='airtime4'),
    url(r'^airtime5/$', airtime5_view, name='airtime5'),
    url(r'^airtime6/$', airtime6_view, name='airtime6'),
    url(r'^mtn1/$', mtn1_view, name='mtn1'),
    url(r'^mtn2/$', mtn2_view, name='mtn2'),
    url(r'^mtn3/$', mtn3_view, name='mtn3'),
    url(r'^mtn4/$', mtn4_view, name='mtn4'),
    url(r'^mtn5/$', mtn5_view, name='mtn5'),
    url(r'^mtn6/$', mtn6_view, name='mtn6'),
    url(r'^mtn7/$', mtn7_view, name='mtn7'),
    url(r'^mtn8/$', mtn8_view, name='mtn8'),
    url(r'^mtn9/$', mtn9_view, name='mtn9'),
    url(r'^mtn10/$', mtn10_view, name='mtn10'),
    url(r'^glo1/$', glo1_view, name='glo1'),
    url(r'^glo2/$', glo2_view, name='glo2'),
    url(r'^glo3/$', glo3_view, name='glo3'),
    url(r'^glo4/$', glo4_view, name='glo4'),
    url(r'^glo5/$', glo5_view, name='glo5'),
    url(r'^glo6/$', glo6_view, name='glo6'),
    url(r'^glo7/$', glo7_view, name='glo7'),
    url(r'^glo8/$', glo8_view, name='glo8'),
    url(r'^glo9/$', glo9_view, name='glo9'),
    url(r'^glo10/$', glo10_view, name='glo10'),
    url(r'^airtel1/$', airtel1_view, name='airtel1'),
    url(r'^airtel2/$', airtel2_view, name='airtel2'),
    url(r'^airtel3/$', airtel3_view, name='airtel3'),
    url(r'^airtel4/$', airtel4_view, name='airtel4'),
    url(r'^airtel5/$', airtel5_view, name='airtel5'),
    url(r'^airtel6/$', airtel6_view, name='airtel6'),
    url(r'^airtel7/$', airtel7_view, name='airtel7'),
    url(r'^airtel8/$', airtel8_view, name='airtel8'),
    url(r'^dstv1/$', dstv1_view, name='dstv1'),
    url(r'^dstv2/$', dstv2_view, name='dstv2'),
    url(r'^dstv3/$', dstv3_view, name='dstv3'),
    url(r'^dstv4/$', dstv4_view, name='dstv4'),
    url(r'^dstv5/$', dstv5_view, name='dstv5'),
    url(r'^dstv6/$', dstv6_view, name='dstv6'),
    url(r'^dstv7/$', dstv7_view, name='dstv7'),
    url(r'^dstv8/$', dstv8_view, name='dstv8'),
    url(r'^dstv9/$', dstv9_view, name='dstv9'),
    url(r'^dstv10/$', dstv10_view, name='dstv10'),
    url(r'^startime1/$', startime1_view, name='startime1'),
    url(r'^startime2/$', startime2_view, name='startime2'),
    url(r'^startime3/$', startime3_view, name='startime3'),
    url(r'^startime4/$', startime4_view, name='startime4'),
    url(r'^startime5/$', startime5_view, name='startime5'),
    url(r'^startime6/$', startime6_view, name='startime6'),
    url(r'^startime7/$', startime7_view, name='startime7'),
    url(r'^startime8/$', startime8_view, name='startime8'),
    url(r'^startime9/$', startime9_view, name='startime9'),
    url(r'^startime10/$', startime10_view, name='startime10'),
    url(r'^startime11/$', startime11_view, name='startime11'),
    url(r'^startime12/$', startime12_view, name='startime12'),
    url(r'^startime13/$', startime13_view, name='startime13'),
    url(r'^elect1/$', elect1_view, name='elect1'),
    url(r'^elect2/$', elect2_view, name='elect2'),
    url(r'^elect3/$', elect3_view, name='elect3'),
    url(r'^elect4/$', elect4_view, name='elect4'),
    url(r'^elect5/$', elect5_view, name='elect5'),
    url(r'^elect6/$', elect6_view, name='elect6'),
    url(r'^elect7/$', elect7_view, name='elect7'),
    url(r'^elect8/$', elect8_view, name='elect8'),
    url(r'^waec/$', waec_view, name='waec'),
    url(r'^neco/$', neco_view, name='neco'),
    url(r'^gotv1/$', gotv1_view, name='gotv1'),
    url(r'^gotv2/$', gotv2_view, name='gotv2'),
    url(r'^gotv3/$', gotv3_view, name='gotv3'),
    url(r'^gotv4/$', gotv4_view, name='gotv4'),
    url(r'^gotv5/$', gotv5_view, name='gotv5'),
    url(r'^gotv6/$', gotv6_view, name='gotv6'),
    url(r'^order1/$', views.order1_view.as_view(), name='order1'),
    url(r'^order2/$', views.order2_view.as_view(), name='order2'),
    url(r'^order3/$', views.order3_view.as_view(), name='order3'),
    url(r'^order4/$', views.order4_view.as_view(), name='order4'),
    url(r'^order5/$', views.order5_view.as_view(), name='order5'),
    url(r'^order6/$', views.order6_view.as_view(), name='order6'),
    url(r'^order7/$', views.order7_view.as_view(), name='order7'),
    url(r'^order8/$', views.order8_view.as_view(), name='order8'),
    url(r'^order9/$', views.order9_view.as_view(), name='order9'),
    url(r'^deposit/$', views.deposit_view.as_view(), name='deposit'),
    
 #   path('/',views.JambView.as_view(),name='jamb'),

          
    
]
