# Generated by Django 3.2.5 on 2022-03-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_withdrawal_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.TextField(max_length=10),
        ),
    ]
