# Generated by Django 3.0.8 on 2022-04-15 10:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20220414_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bank_details',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='phone_number',
            field=models.IntegerField(blank=True, default=1234, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diposit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('3000.00'))]),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
