# Generated by Django 3.0.8 on 2022-04-21 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0008_auto_20220420_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTN_2GB_SME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Number', models.IntegerField(blank=True)),
                ('Confirmation', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtn3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='mtn_10gb_sme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtn7', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mtn_1gb_wd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtn8', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mtn_1p5gb_md',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtn10', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mtn_20gb_wd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtn12', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mtn_2gb_md',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtn11', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mtn_3gb_sme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtn4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mtn_4gb_sme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtn5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mtn_5gb_sme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtn6', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MTN_6GB_WD',
        ),
    ]
