# Generated by Django 3.0.8 on 2022-04-22 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0010_airtel_dstv_electricity_exam_glo_gotv_mtn_startimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtn_500mb_sme',
            name='Confirmation',
        ),
        migrations.AlterField(
            model_name='mtn_500mb_sme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtn_500mb_smes', to=settings.AUTH_USER_MODEL),
        ),
    ]
