# Generated by Django 3.0.8 on 2022-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20220423_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dstv_asian_addon',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dstv_compact_plus',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dstv_compact_plus_asian_addon',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dstv_compact_plus_f',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dstv_confam',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dstv_french_bouguet',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dstv_padi',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dstv_premium',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dstv_xtraview',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dstv_yanga',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='elect_eko_post',
            name='Meter_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='elect_eko_pre',
            name='Meter_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='elect_enugu_post',
            name='Meter_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='elect_enugu_pre',
            name='Meter_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='elect_ibadan_post',
            name='Meter_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='elect_ibadan_pre',
            name='Meter_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='elect_ikeja_post',
            name='Meter_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='elect_ikeja_pre',
            name='Meter_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gotv_jinja',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gotv_jolli',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gotv_lite_quart',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gotv_lite_year',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gotv_max',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gotv_smallie',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_basic_d',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_basic_m',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_basic_w',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_classic_d',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_classic_m',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_classic_w',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_nova_d',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_nova_m',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_nova_w',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_smart_d',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_smart_m',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='startime_smart_w',
            name='Smart_Card_Number_or_IUC',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
