# Generated by Django 3.0.8 on 2022-04-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20220423_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startime_smart_w',
            name='Smart_Card_Number_or_IUC',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
